Create the navbar #21
marroe01284/NEXUS pull request #27
Opened 2024-03-18 19:37 UTC by TomChrister

2024-03-18 20:03 UTC, KjetilHHauger approved these changes
Ah ok, ser greit ut på koden

2024-03-18 20:03 UTC, KjetilHHauger commented on index.html
>      <link rel="stylesheet" href="css/exuser.css">
Tror ikke css/exuser.css finnes lenger

2024-03-18 20:03 UTC, KjetilHHauger commented on index.html
>      <link rel="stylesheet" href="css/exuser.css">
Glem det

2024-03-18 20:05 UTC, KjetilHHauger commented on index.html
> +                Terms Privacy Policy <br>
Kan linke til terms siden og privacy siden. Di andre kan ha en link til href=#

2024-03-18 20:08 UTC, KjetilHHauger commented on index.html
> +        <div class="header-content-logo">
Ser ingen linker er linka enda

2024-03-18 21:04 UTC, KjetilHHauger requested changes

2024-03-18 21:04 UTC, KjetilHHauger commented on index.html
> +</header>
Mangler linker

2024-03-18 21:04 UTC, KjetilHHauger commented on index.html
> +</header>
link til html eller til #

2024-03-19 09:08 UTC, marroe01284 approved these changes
css looks good, nice following the principles we have set.

2024-03-19 09:10 UTC, marroe01284 approved these changes
structure wise it looks good, remember that the next step would be to add all the links witch directs the user to the right pages, if the pages are not set atm just add the # for the moment.

2024-03-19 09:14 UTC, marroe01284 commented on index.html
idex.html er login page den har ikke navbar, du må bruke html sidene som har en navbar se i figma.

2024-03-19 11:33 UTC, TomChrister reviewed
changes are done

2024-03-19 11:34 UTC, TomChrister reviewed
changes are done

2024-03-19 11:51 UTC, KjetilHHauger approved these changes

2024-03-19 11:52 UTC, merged